# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/tubiao.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpenShp = QtWidgets.QAction(MainWindow)
        self.actionOpenShp.setObjectName("actionOpenShp")
        self.actionOpenRaster = QtWidgets.QAction(MainWindow)
        self.actionOpenRaster.setObjectName("actionOpenRaster")
        self.actionEditShp = QtWidgets.QAction(MainWindow)
        self.actionEditShp.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditShp.setIcon(icon1)
        self.actionEditShp.setObjectName("actionEditShp")
        self.actionSelectFeature = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/png/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectFeature.setIcon(icon2)
        self.actionSelectFeature.setObjectName("actionSelectFeature")
        self.actionDeleteFeature = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/png/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteFeature.setIcon(icon3)
        self.actionDeleteFeature.setObjectName("actionDeleteFeature")
        self.actionOpenS57 = QtWidgets.QAction(MainWindow)
        self.actionOpenS57.setObjectName("actionOpenS57")
        self.menuEdit.addAction(self.actionEditShp)
        self.menuEdit.addAction(self.actionSelectFeature)
        self.menuEdit.addAction(self.actionDeleteFeature)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.actionOpenShp)
        self.toolBar.addAction(self.actionOpenRaster)
        self.toolBar.addAction(self.actionOpenS57)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuOpen.setTitle(_translate("MainWindow", "打开"))
        self.menuEdit.setTitle(_translate("MainWindow", "编辑"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpenShp.setText(_translate("MainWindow", "打开矢量"))
        self.actionOpenRaster.setText(_translate("MainWindow", "打开栅格"))
        self.actionEditShp.setText(_translate("MainWindow", "编辑矢量"))
        self.actionSelectFeature.setText(_translate("MainWindow", "选择要素"))
        self.actionDeleteFeature.setText(_translate("MainWindow", "删除选中要素"))
        self.actionOpenS57.setText(_translate("MainWindow", "打开s57格式海图"))
import myRc_rc
